dataset_name: cifar10
arch: resnet18
epochs: 100
warmup_epochs: 10
batch_size: 256
lr: null
weight_decay: 0.000001
temperature: 0.1
seed: 42
out_dim: 128
n_views: 2
workers: 2
fp16_precision: true
log_every_n_steps: 100
